<?php
declare(strict_types=1);

$pageTitle = 'Teacher Applicant Pool';
require_once dirname(__DIR__, 3) . '/includes/header.php';
requireApplicantModuleAccess();
$db = getDB();
requireApplicantModuleSchema($db);
$refs = applicantReferenceData($db);
$scope = applicantDistrictScope();
$view = trim((string)($_GET['view'] ?? ''));
$tab = trim((string)($_GET['tab'] ?? 'applicants'));
if (!in_array($tab, ['applicants','requests','active','history'], true)) $tab = 'applicants';

$decodeId = static function(string $token): int {
    if ($token === '') return 0;
    if (ctype_digit($token)) return (int)$token;
    $id = decryptId($token);
    return $id === false ? 0 : $id;
};
$tokenId = $decodeId(trim((string)($_GET['id'] ?? '')));
$districtsSql = 'SELECT d.id,d.district_name FROM districts d WHERE ' . activeArchiveExclusion('district', 'd.id');
$districtParams = [];
if ($scope !== null) { $districtsSql .= ' AND d.id=?'; $districtParams[] = $scope; }
$districtsSql .= ' ORDER BY d.district_name';
$districtStmt = $db->prepare($districtsSql);
$districtStmt->execute($districtParams);
$districts = $districtStmt->fetchAll(PDO::FETCH_ASSOC);
$municipalities = $db->query("SELECT id,municipality_name FROM municipalities WHERE province_name='Aurora' ORDER BY municipality_name")->fetchAll(PDO::FETCH_ASSOC);

$levelLabels = ['elementary'=>'Elementary','jhs'=>'Junior High School','shs'=>'Senior High School'];
$badge = static fn(string $value): string => '<span class="badge badge-blue">' . clean(ucwords(str_replace('_', ' ', $value))) . '</span>';
?>
<style>
.applicant-head{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:14px}.applicant-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.applicant-tabs a{text-decoration:none}.applicant-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.applicant-section{padding:16px;margin-bottom:14px}.applicant-section h3{margin:0 0 14px}.score-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.score-total{font-size:1.35rem;font-weight:800;color:#67e8f9}.match-card{padding:14px;margin-bottom:10px;border-left:4px solid #22c55e}.match-card.outside{border-left-color:#f59e0b}.match-explain{margin:8px 0;padding-left:18px;color:#cbd5e1}.privacy-note{padding:10px 12px;border:1px solid rgba(245,158,11,.35);border-radius:10px;background:rgba(245,158,11,.08);color:#fde68a}.nowrap{white-space:nowrap}.status-open{color:#86efac}.status-closed{color:#fca5a5}@media(max-width:720px){.data-table{min-width:900px}.applicant-head .btn{width:100%}}
</style>

<div class="applicant-head">
    <div><h1 style="margin:0;"><i class="fas fa-user-graduate"></i> Teacher Applicant Pool</h1></div>
    <div style="display:flex;gap:8px;flex-wrap:wrap;">
        <?php if (canCreateSubstituteRequest()): ?><a class="btn btn-secondary" href="<?= APP_URL ?>/applicants.php?view=request_form"><i class="fas fa-file-circle-plus"></i> Request Substitute</a><?php endif; ?>
        <?php if (canManageApplicants()): ?><a class="btn btn-primary" href="<?= APP_URL ?>/applicants.php?view=form"><i class="fas fa-user-plus"></i> Add Applicant</a><?php endif; ?>
    </div>
</div>

<div class="applicant-tabs">
<?php foreach (['applicants'=>'Applicants','requests'=>'Substitute Requests','active'=>'Active Assignments','history'=>'Assignment History'] as $key=>$label): ?>
    <a class="btn <?= $tab === $key && $view === '' ? 'btn-primary' : 'btn-ghost' ?>" href="<?= APP_URL ?>/applicants.php?tab=<?= $key ?>"><?= clean($label) ?></a>
<?php endforeach; ?>
</div>

<?php if ($view === 'form' && canManageApplicants()): ?>
<?php
$editing = $tokenId > 0;
$formState = pullFormState('applicant.form');
$errors = $formState['errors'];
$data = $formState['data'];
if ($editing && !$data) {
    $stmt = $db->prepare('SELECT a.*,sc.*,l.*,l.municipality_id location_municipality_id FROM teacher_applicants a INNER JOIN teacher_applicant_scores sc ON sc.applicant_id=a.id INNER JOIN teacher_applicant_locations l ON l.applicant_id=a.id WHERE a.id=?');
    $stmt->execute([$tokenId]);
    $data = $stmt->fetch(PDO::FETCH_ASSOC) ?: [];
    if ($data) { $data['municipality_id'] = $data['location_municipality_id']; $data['address_line'] = decryptSensitiveApplicantValue($data['address_line_encrypted'] ?? null); }
}
if ($editing && (!$data || ($scope !== null && $scope !== (int)$data['district_id']))):
    echo '<div class="alert alert-error">Applicant not found or outside your district.</div>';
else:
$selectedLevel = (string)($data['level'] ?? '');
if ($editing) logActivity('VIEW', 'applicant_sensitive_location', $tokenId, 'Viewed restricted applicant contact and location details for editing.');
?>
<form method="POST" action="<?= APP_URL ?>/actions/manage_applicant.php" id="applicantForm">
<input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= $editing ? $tokenId : 0 ?>">
<?php if (!empty($errors['form'])): ?><div class="alert alert-error"><?= clean($errors['form']) ?></div><?php endif; ?>
<section class="glass-card applicant-section"><h3>Personal and Application Information</h3><div class="applicant-grid">
<?php foreach (['last_name'=>'Last Name','first_name'=>'First Name','middle_name'=>'Middle Name'] as $field=>$label): ?><div class="form-group"><label class="form-label <?= $field !== 'middle_name' ? 'required' : '' ?>"><?= $label ?></label><input class="form-input" name="<?= $field ?>" value="<?= clean($data[$field] ?? '') ?>" maxlength="80" <?= $field !== 'middle_name' ? 'required minlength="2"' : '' ?> pattern="[\p{L}\p{M} .'-]+"><small class="form-error"><?= clean($errors[$field] ?? '') ?></small></div><?php endforeach; ?>
<div class="form-group"><label class="form-label required">Application Code</label><input class="form-input" name="application_code" value="<?= clean($data['application_code'] ?? '') ?>" minlength="3" maxlength="50" pattern="[A-Za-z0-9_\/-]+" required><small class="form-error"><?= clean($errors['application_code'] ?? '') ?></small></div>
<div class="form-group"><label class="form-label required">Email Address</label><input type="email" class="form-input" name="email_address" value="<?= clean($data['email_address'] ?? '') ?>" maxlength="254" required><small class="form-error"><?= clean($errors['email_address'] ?? '') ?></small></div>
<div class="form-group"><label class="form-label required">Contact Number</label><input class="form-input" name="contact_number" value="<?= clean($data['contact_number'] ?? '') ?>" inputmode="numeric" minlength="10" maxlength="15" pattern="[0-9]{10,15}" required><small class="form-error"><?= clean($errors['contact_number'] ?? '') ?></small></div>
<div class="form-group"><label class="form-label required">Level</label><select class="form-select" name="level" id="applicantLevel" required><option value="">Select level</option><?php foreach ($levelLabels as $key=>$label): ?><option value="<?= $key ?>" <?= $selectedLevel===$key?'selected':'' ?>><?= clean($label) ?></option><?php endforeach; ?></select><small class="form-error"><?= clean($errors['level'] ?? '') ?></small></div>
<div class="form-group"><label class="form-label required">Specialization</label><select class="form-select" name="specialization_id" id="applicantSpecialization" required><option value="">Select specialization</option><?php foreach ($refs['specializations'] as $spec): ?><option value="<?= (int)$spec['id'] ?>" data-name="<?= clean($spec['name']) ?>" data-elementary="<?= (int)$spec['allowed_elementary'] ?>" data-jhs="<?= (int)$spec['allowed_jhs'] ?>" data-shs="<?= (int)$spec['allowed_shs'] ?>" <?= (int)($data['specialization_id']??0)===(int)$spec['id']?'selected':'' ?>><?= clean($spec['name']) ?></option><?php endforeach; ?></select><small class="form-error"><?= clean($errors['specialization_id'] ?? '') ?></small></div>
<div class="form-group"><label class="form-label required">District</label><select class="form-select" name="district_id" required><option value="">Select district</option><?php foreach ($districts as $district): ?><option value="<?= (int)$district['id'] ?>" <?= (int)($data['district_id']??0)===(int)$district['id']?'selected':'' ?>><?= clean($district['district_name']) ?></option><?php endforeach; ?></select><small class="form-error"><?= clean($errors['district_id'] ?? '') ?></small></div>
<div class="form-group"><label class="form-label required">Application Status</label><select class="form-select" name="application_status_id" required><?php foreach ($refs['application_statuses'] as $status): ?><option value="<?= (int)$status['id'] ?>" <?= (int)($data['application_status_id']??0)===(int)$status['id']?'selected':'' ?>><?= clean($status['label']) ?></option><?php endforeach; ?></select><small class="form-error"><?= clean($errors['application_status_id'] ?? '') ?></small></div>
<div class="form-group"><label class="form-label required">Availability</label><select class="form-select" name="availability_status_id" required><?php foreach ($refs['availability_statuses'] as $status): ?><option value="<?= (int)$status['id'] ?>" <?= (int)($data['availability_status_id']??0)===(int)$status['id']?'selected':'' ?>><?= clean($status['label']) ?></option><?php endforeach; ?></select><small class="form-error"><?= clean($errors['availability_status_id'] ?? '') ?></small></div>
</div><div class="form-group" style="margin-top:12px;"><label class="form-label">Remarks from RQA</label><textarea class="form-input" name="rqa_remarks" maxlength="1000" rows="3"><?= clean($data['rqa_remarks'] ?? '') ?></textarea><small class="form-error"><?= clean($errors['rqa_remarks'] ?? '') ?></small></div></section>

<section class="glass-card applicant-section"><h3>Residential Address</h3><div class="privacy-note">Distance is estimated from the selected PSGC barangay. Latitude, longitude, and residential map pins are not collected or displayed.</div><div class="applicant-grid" style="margin-top:12px;">
<div class="form-group"><label class="form-label">Address Line</label><input class="form-input" name="address_line" maxlength="255" value="<?= clean($data['address_line'] ?? '') ?>"><small class="text-muted">Encrypted at rest; optional.</small></div>
<div class="form-group"><label class="form-label required">Municipality</label><select class="form-select" name="municipality_id" id="applicantMunicipality" required><option value="">Select municipality</option><?php foreach ($municipalities as $municipality): ?><option value="<?= (int)$municipality['id'] ?>" <?= (int)($data['municipality_id']??0)===(int)$municipality['id']?'selected':'' ?>><?= clean($municipality['municipality_name']) ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label class="form-label required">Barangay</label><select class="form-select" name="barangay_psgc_code" id="applicantBarangay" required data-selected-code="<?= clean($data['barangay_psgc_code'] ?? '') ?>"><?php if (!empty($data['barangay'])): ?><option value="<?= clean($data['barangay_psgc_code']) ?>" data-name="<?= clean($data['barangay']) ?>" selected><?= clean($data['barangay']) ?></option><?php else: ?><option value="">Select municipality first…</option><?php endif; ?></select><input type="hidden" name="barangay" id="applicantBarangayName" value="<?= clean($data['barangay'] ?? '') ?>"><small id="applicantAddressStatus" class="text-muted"><?= clean($errors['address'] ?? '') ?></small></div>
<div class="form-group"><label class="form-label">Province</label><input class="form-input" value="Aurora" readonly></div>
</div></section>

<section class="glass-card applicant-section"><h3>RQA Score Breakdown</h3><div class="score-grid"><?php foreach (['education'=>'Education','training'=>'Training','experience'=>'Experience','let_pbet_rating'=>'LET/PBET Rating','coi'=>'COI','ncoi'=>'NCOI'] as $field=>$label): ?><div class="form-group"><label class="form-label"><?= $label ?></label><input type="number" min="0" step="0.01" class="form-input applicant-score" name="<?= $field ?>" value="<?= clean($data[$field] ?? '0.00') ?>"><small class="form-error"><?= clean($errors[$field] ?? '') ?></small></div><?php endforeach; ?><div class="form-group"><label class="form-label">Total Rating</label><output class="form-input score-total" id="applicantTotal"><?= number_format((float)($data['total_rating'] ?? 0),2) ?></output><small class="text-muted">Calculated again by the server.</small></div></div></section>
<div class="modal-actions"><a class="btn btn-ghost" href="<?= APP_URL ?>/applicants.php">Cancel</a><button class="btn btn-primary" type="submit"><i class="fas fa-save"></i> Save Applicant</button></div>
</form>
<script src="<?= APP_URL ?>/assets/js/aurora-address.js"></script>
<script>
initializeAuroraAddressPicker({
    endpoint: <?= json_encode(APP_URL . '/actions/address_options.php', JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>,
    municipalitySelectId:'applicantMunicipality',
    barangaySelectId:'applicantBarangay',
    barangayNameInputId:'applicantBarangayName',
    statusId:'applicantAddressStatus'
});
const level=document.getElementById('applicantLevel'),spec=document.getElementById('applicantSpecialization');
function filterApplicantSpecs(){const selected=level.value;let first='';[...spec.options].forEach((o,i)=>{if(i===0)return;const allowed=o.dataset[selected]==='1';o.hidden=!allowed;o.disabled=!allowed;if(allowed&&!first)first=o.value});if(selected==='elementary'){const general=[...spec.options].find(o=>o.dataset.name==='General Education');if(general)spec.value=general.value}else if(spec.selectedOptions[0]?.disabled)spec.value=''}
level.addEventListener('change',filterApplicantSpecs);filterApplicantSpecs();
function totalScores(){let total=0;document.querySelectorAll('.applicant-score').forEach(i=>{const n=Number(i.value);if(Number.isFinite(n)&&n>=0)total+=n});document.getElementById('applicantTotal').textContent=total.toFixed(2)}document.querySelectorAll('.applicant-score').forEach(i=>i.addEventListener('input',totalScores));totalScores();
</script>
<?php endif; ?>

<?php elseif ($view === 'applicant'): ?>
<?php
$stmt = $db->prepare('SELECT a.*,sp.name specialization_name,d.district_name,aps.label application_status,avs.label availability_status,avs.code availability_code,sc.*,l.*,t.first_name linked_first,t.last_name linked_last FROM teacher_applicants a INNER JOIN teacher_specializations sp ON sp.id=a.specialization_id INNER JOIN districts d ON d.id=a.district_id INNER JOIN applicant_application_statuses aps ON aps.id=a.application_status_id INNER JOIN applicant_availability_statuses avs ON avs.id=a.availability_status_id INNER JOIN teacher_applicant_scores sc ON sc.applicant_id=a.id INNER JOIN teacher_applicant_locations l ON l.applicant_id=a.id LEFT JOIN teachers t ON t.id=a.linked_teacher_id WHERE a.id=?');
$stmt->execute([$tokenId]); $applicant=$stmt->fetch(PDO::FETCH_ASSOC);
if (!$applicant || ($scope!==null && $scope!==(int)$applicant['district_id'])): ?> <div class="alert alert-error">Applicant not found or outside your district.</div>
<?php else:
$history=$db->prepare('SELECT sa.*,s.school_name,sr.request_code FROM substitute_assignments sa INNER JOIN schools s ON s.id=sa.school_id INNER JOIN substitute_requests sr ON sr.id=sa.substitute_request_id WHERE sa.applicant_id=? ORDER BY sa.assigned_at DESC');$history->execute([$tokenId]);$assignments=$history->fetchAll(PDO::FETCH_ASSOC);
if (canViewApplicantSensitiveLocation()) logActivity('VIEW', 'applicant_sensitive_location', $tokenId, 'Viewed restricted applicant contact and location details.');
?>
<section class="glass-card applicant-section"><div class="applicant-head"><div><h2><?= clean($applicant['last_name'].', '.$applicant['first_name'].' '.$applicant['middle_name']) ?></h2><span class="badge badge-blue"><?= clean($applicant['application_code']) ?></span> <?= $badge($applicant['application_status']) ?> <?= $badge($applicant['availability_status']) ?></div><?php if(canManageApplicants()): ?><a class="btn btn-primary" href="<?= APP_URL ?>/applicants.php?view=form&id=<?= urlencode(encryptId($tokenId)) ?>">Edit Applicant</a><?php endif; ?></div>
<div class="applicant-grid"><div><strong>Level</strong><p><?= clean($levelLabels[$applicant['level']]??$applicant['level']) ?></p></div><div><strong>Specialization</strong><p><?= clean($applicant['specialization_name']) ?></p></div><div><strong>District</strong><p><?= clean($applicant['district_name']) ?></p></div><div><strong>Contact</strong><p><?= canViewApplicantSensitiveLocation()?clean($applicant['contact_number'].' · '.$applicant['email_address']):'Restricted' ?></p></div><div><strong>Residential Area</strong><p><?= clean($applicant['barangay'].', '.$applicant['municipality'].', Aurora') ?></p></div><div><strong>Distance Basis</strong><p>PSGC barangay approximation</p></div></div>
<?php if(canViewApplicantSensitiveLocation()): ?><div class="privacy-note"><strong>Restricted exact address:</strong> <?= clean(decryptSensitiveApplicantValue($applicant['address_line_encrypted'])) ?: 'Not provided' ?>. Distance calculations use only the barangay approximation.</div><?php endif; ?>
</section>
<section class="glass-card applicant-section"><h3>Score Breakdown</h3><div class="score-grid"><?php foreach(['education'=>'Education','training'=>'Training','experience'=>'Experience','let_pbet_rating'=>'LET/PBET','coi'=>'COI','ncoi'=>'NCOI','total_rating'=>'Total'] as $field=>$label): ?><div><strong><?= $label ?></strong><p class="<?= $field==='total_rating'?'score-total':'' ?>"><?= number_format((float)$applicant[$field],2) ?></p></div><?php endforeach; ?></div></section>
<section class="glass-card applicant-section"><h3>Substitute Assignment History</h3><div class="table-scroll"><table class="data-table"><thead><tr><th>Request</th><th>School</th><th>Period</th><th>Status</th><th>Distance Used</th><th>Rating Used</th></tr></thead><tbody><?php foreach($assignments as $assignment): ?><tr><td><?= clean($assignment['request_code']) ?></td><td><?= clean($assignment['school_name']) ?></td><td><?= clean($assignment['start_date'].' to '.$assignment['expected_end_date']) ?></td><td><?= $badge($assignment['assignment_status']) ?></td><td><?= $assignment['road_distance_km']!==null?number_format((float)$assignment['road_distance_km'],2).' km':'Unavailable' ?></td><td><?= number_format((float)$assignment['rating_used'],2) ?></td></tr><?php endforeach; ?><?php if(!$assignments): ?><tr><td colspan="6" class="text-center text-muted">No assignment history.</td></tr><?php endif; ?></tbody></table></div></section>
<?php if(canManageApplicants()): ?><section class="glass-card applicant-section"><h3>Lifecycle Actions</h3><div style="display:flex;gap:10px;flex-wrap:wrap;"><?php if((int)$applicant['is_active']===1 && $applicant['availability_code']!=='permanently_deployed'): ?><form method="POST" action="<?= APP_URL ?>/actions/manage_applicant.php"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="deactivate"><input type="hidden" name="id" value="<?= $tokenId ?>"><input class="form-input" name="reason" maxlength="255" required placeholder="Required deactivation reason" style="display:inline-block;width:260px"><button class="btn btn-danger">Deactivate</button></form><?php elseif((int)$applicant['is_active']===0): ?><form method="POST" action="<?= APP_URL ?>/actions/manage_applicant.php"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="activate"><input type="hidden" name="id" value="<?= $tokenId ?>"><button class="btn btn-primary">Reactivate</button></form><?php endif; ?><?php if($applicant['availability_code']!=='permanently_deployed'): ?><form method="POST" action="<?= APP_URL ?>/actions/manage_applicant.php"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="permanent_deploy"><input type="hidden" name="id" value="<?= $tokenId ?>"><select class="form-select" name="linked_teacher_id" required style="display:inline-block;width:280px"><option value="">Link permanent teacher…</option><?php foreach($db->query('SELECT id,last_name,first_name FROM teachers WHERE '.activeArchiveExclusion('teacher','teachers.id').' ORDER BY last_name,first_name')->fetchAll() as $teacher): ?><option value="<?= (int)$teacher['id'] ?>"><?= clean($teacher['last_name'].', '.$teacher['first_name']) ?></option><?php endforeach; ?></select><button class="btn btn-secondary">Mark Permanently Deployed</button></form><?php endif; ?></div></section><?php endif; ?>
<?php endif; ?>

<?php elseif ($view === 'request_form' && canCreateSubstituteRequest()): ?>
<?php
$state=pullFormState('substitute.request');$data=$state['data'];$errors=$state['errors'];
$editingRequest = $tokenId > 0 && canManageApplicants();
if ($editingRequest && !$data) {
    $requestEdit = $db->prepare('SELECT * FROM substitute_requests WHERE id=?');
    $requestEdit->execute([$tokenId]);
    $data = $requestEdit->fetch(PDO::FETCH_ASSOC) ?: [];
    if (!$data || ($scope !== null && $scope !== (int)($data['school_district_id'] ?? 0))) {
        $editingRequest = false;
        $data = [];
        $errors['form'] = 'Request not found or outside your district.';
    }
}
$schoolContext = $decodeId(trim((string)($_GET['school'] ?? '')));
if (!$data && $schoolContext > 0) $data['school_id'] = $schoolContext;
$schoolSql='SELECT s.id,s.school_name,s.district_id FROM schools s WHERE '.activeArchiveExclusion('school','s.id');$params=[];if($scope!==null){$schoolSql.=' AND s.district_id=?';$params[]=$scope;}$schoolSql.=' ORDER BY s.school_name';$st=$db->prepare($schoolSql);$st->execute($params);$schools=$st->fetchAll(PDO::FETCH_ASSOC);
$teachers=$db->query('SELECT id,school_id,last_name,first_name FROM teachers WHERE '.activeArchiveExclusion('teacher','teachers.id').' ORDER BY last_name,first_name')->fetchAll(PDO::FETCH_ASSOC);
?>
<form method="POST" action="<?= APP_URL ?>/actions/manage_substitute_request.php" class="glass-card applicant-section" id="requestForm"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="<?= $editingRequest ? 'save' : 'create' ?>"><input type="hidden" name="id" value="<?= $editingRequest ? $tokenId : 0 ?>"><input type="hidden" name="submission_token" value="<?= bin2hex(random_bytes(32)) ?>"><h3><?= $editingRequest ? 'Edit' : 'Request' ?> Substitute Teacher</h3><?php if(!empty($errors['form'])): ?><div class="alert alert-error"><?= clean($errors['form']) ?></div><?php endif; ?><p class="privacy-note">Use only a general authorized leave reason. Do not enter medical diagnoses or other sensitive clinical details.</p><div class="applicant-grid" style="margin-top:12px;">
<div class="form-group"><label class="form-label required">School</label><select class="form-select" name="school_id" id="requestSchool" required><option value="">Select school</option><?php foreach($schools as $school): ?><option value="<?= (int)$school['id'] ?>" <?= (int)($data['school_id']??0)===(int)$school['id']?'selected':'' ?>><?= clean($school['school_name']) ?></option><?php endforeach; ?></select><small class="form-error"><?= clean($errors['school_id']??'') ?></small></div>
<div class="form-group"><label class="form-label required">Level</label><select class="form-select" name="level" id="requestLevel" required><option value="">Select level</option><?php foreach($levelLabels as $key=>$label): ?><option value="<?= $key ?>" <?= ($data['level']??'')===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select><small class="form-error"><?= clean($errors['level']??'') ?></small></div>
<div class="form-group"><label class="form-label required">Required Specialization</label><select class="form-select" name="specialization_id" id="requestSpecialization" required><option value="">Select specialization</option><?php foreach($refs['specializations'] as $spec): ?><option value="<?= (int)$spec['id'] ?>" data-name="<?= clean($spec['name']) ?>" data-elementary="<?= (int)$spec['allowed_elementary'] ?>" data-jhs="<?= (int)$spec['allowed_jhs'] ?>" data-shs="<?= (int)$spec['allowed_shs'] ?>" <?= (int)($data['specialization_id']??0)===(int)$spec['id']?'selected':'' ?>><?= clean($spec['name']) ?></option><?php endforeach; ?></select><small class="form-error"><?= clean($errors['specialization_id']??'') ?></small></div>
<div class="form-group"><label class="form-label">Permanent Teacher Being Substituted</label><select class="form-select" name="permanent_teacher_id" id="requestTeacher"><option value="0">Not specified</option><?php foreach($teachers as $teacher): ?><option value="<?= (int)$teacher['id'] ?>" data-school="<?= (int)$teacher['school_id'] ?>" <?= (int)($data['permanent_teacher_id']??0)===(int)$teacher['id']?'selected':'' ?>><?= clean($teacher['last_name'].', '.$teacher['first_name']) ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label class="form-label required">General Leave Reason</label><select class="form-select" name="leave_reason" required><?php foreach(['Maternity Leave','Study Leave','Extended Sick Leave','Other Authorized Leave'] as $reason): ?><option <?= ($data['leave_reason']??'')===$reason?'selected':'' ?>><?= $reason ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label class="form-label required">Leave Start</label><input type="date" class="form-input" name="leave_start_date" id="leaveStart" value="<?= clean($data['leave_start_date']??'') ?>" required></div><div class="form-group"><label class="form-label required">Expected Return/End</label><input type="date" class="form-input" name="expected_end_date" id="leaveEnd" value="<?= clean($data['expected_end_date']??'') ?>" required><small class="form-error"><?= clean($errors['expected_end_date']??'') ?></small></div>
<div class="form-group"><label class="form-label">Computed Duration</label><output class="form-input" id="leaveDuration">—</output><small class="text-muted">Must be more than <?= substituteMinimumLeaveDays($db) ?> days.</small></div><div class="form-group"><label class="form-label required">Substitutes Needed</label><input type="number" class="form-input" name="substitutes_needed" min="1" max="20" value="<?= (int)($data['substitutes_needed']??1) ?>" required></div>
<div class="form-group"><label class="form-label required">Initial Status</label><select class="form-select" name="status"><option value="pending_validation" <?= ($data['status']??'pending_validation')==='pending_validation'?'selected':'' ?>>Pending Validation</option><option value="draft" <?= ($data['status']??'')==='draft'?'selected':'' ?>>Draft</option><?php if(canManageApplicants()): ?><option value="open" <?= ($data['status']??'')==='open'?'selected':'' ?>>Open</option><?php endif; ?></select></div></div><div class="form-group"><label class="form-label">Request Remarks</label><textarea class="form-input" name="request_remarks" maxlength="1000" rows="3"><?= clean($data['request_remarks']??'') ?></textarea></div><div class="modal-actions"><a class="btn btn-ghost" href="<?= APP_URL ?>/applicants.php?tab=requests">Cancel</a><button class="btn btn-primary"><?= $editingRequest ? 'Update' : 'Create' ?> Request</button></div></form>
<script>const rl=document.getElementById('requestLevel'),rs=document.getElementById('requestSpecialization'),school=document.getElementById('requestSchool'),teacher=document.getElementById('requestTeacher');function filterRequestSpecs(){const v=rl.value;[...rs.options].forEach((o,i)=>{if(i===0)return;const ok=o.dataset[v]==='1';o.hidden=!ok;o.disabled=!ok});if(v==='elementary'){const g=[...rs.options].find(o=>o.dataset.name==='General Education');if(g)rs.value=g.value}else if(rs.selectedOptions[0]?.disabled)rs.value=''}function filterTeachers(){[...teacher.options].forEach((o,i)=>{if(i===0)return;o.hidden=o.dataset.school!==school.value;o.disabled=o.hidden});if(teacher.selectedOptions[0]?.disabled)teacher.value='0'}function duration(){const a=new Date(document.getElementById('leaveStart').value+'T00:00:00'),b=new Date(document.getElementById('leaveEnd').value+'T00:00:00');document.getElementById('leaveDuration').textContent=Number.isNaN(a.getTime())||Number.isNaN(b.getTime())?'—':Math.floor((b-a)/86400000)+' days'}rl.addEventListener('change',filterRequestSpecs);school.addEventListener('change',filterTeachers);document.getElementById('leaveStart').addEventListener('change',duration);document.getElementById('leaveEnd').addEventListener('change',duration);filterRequestSpecs();filterTeachers();duration();</script>

<?php elseif ($view === 'request'): ?>
<?php
$stmt=$db->prepare('SELECT sr.*,s.school_name,d.district_name,sp.name specialization_name,u.full_name requester_name,t.last_name teacher_last,t.first_name teacher_first FROM substitute_requests sr INNER JOIN schools s ON s.id=sr.school_id INNER JOIN districts d ON d.id=sr.school_district_id INNER JOIN teacher_specializations sp ON sp.id=sr.specialization_id INNER JOIN users u ON u.id=sr.requested_by LEFT JOIN teachers t ON t.id=sr.permanent_teacher_id WHERE sr.id=?');$stmt->execute([$tokenId]);$request=$stmt->fetch(PDO::FETCH_ASSOC);
if(!$request||($scope!==null&&$scope!==(int)$request['school_district_id'])): ?><div class="alert alert-error">Request not found or outside your district.</div>
<?php else:$candidates=in_array($request['status'],['open','partially_filled'],true)?findMatchingApplicants($db,$request,false):[]; ?>
<section class="glass-card applicant-section"><div class="applicant-head"><div><h2><?= clean($request['request_code']) ?></h2><?= $badge($request['status']) ?></div><?php if(canManageApplicants()): ?><div style="display:flex;gap:8px;"><?php foreach(['open'=>'Open','cancelled'=>'Cancel','completed'=>'Complete'] as $status=>$label): ?><form method="POST" action="<?= APP_URL ?>/actions/manage_substitute_request.php"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="set_status"><input type="hidden" name="id" value="<?= $tokenId ?>"><input type="hidden" name="status" value="<?= $status ?>"><button class="btn btn-ghost btn-sm"><?= $label ?></button></form><?php endforeach; ?></div><?php endif; ?></div><div class="applicant-grid"><div><strong>School</strong><p><?= clean($request['school_name']) ?></p></div><div><strong>District</strong><p><?= clean($request['district_name']) ?></p></div><div><strong>Level / Specialization</strong><p><?= clean(($levelLabels[$request['level']]??$request['level']).' · '.$request['specialization_name']) ?></p></div><div><strong>Leave</strong><p><?= clean($request['leave_reason']) ?><br><?= clean($request['leave_start_date'].' to '.$request['expected_end_date']) ?> (<?= (int)$request['duration_days'] ?> days)</p></div><div><strong>Slots</strong><p><?= (int)$request['substitutes_needed'] ?></p></div><div><strong>Requested by</strong><p><?= clean($request['requester_name']) ?></p></div></div></section>
<?php if(canManageApplicants()): ?><div style="margin-bottom:10px"><a class="btn btn-primary btn-sm" href="<?= APP_URL ?>/applicants.php?view=request_form&id=<?= urlencode(encryptId($tokenId)) ?>"><i class="fas fa-edit"></i> Edit Request</a></div><?php endif; ?>
<?php if(in_array($request['status'],['open','partially_filled'],true)): ?><section class="glass-card applicant-section"><div class="applicant-head"><div><h3>Matching Applicants</h3><p class="text-muted">Eligibility: level → specialization. Ranking: same district → known shortest road distance → highest RQA rating.</p></div><?php if(canManageApplicants()): ?><form method="POST" action="<?= APP_URL ?>/actions/manage_substitute_request.php"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="find_matches"><input type="hidden" name="id" value="<?= $tokenId ?>"><button class="btn btn-primary"><i class="fas fa-route"></i> Find Matching Applicants</button></form><?php endif; ?></div>
<?php foreach($candidates as $i=>$candidate): ?><article class="glass-card match-card <?= $candidate['same_district']?'':'outside' ?>"><div class="applicant-head"><div><strong>#<?= $i+1 ?> <?= clean($candidate['full_name']) ?></strong><div><?= $candidate['same_district']?'<span class="badge badge-green">Same District</span>':'<span class="badge badge-warning">Outside District</span>' ?> <?= $candidate['distance']['distance_km']!==null?'<span class="badge badge-blue">'.number_format((float)$candidate['distance']['distance_km'],2).' km · '.clean(formatTravelTime($candidate['distance']['travel_time_seconds'])).'</span>':'<span class="badge badge-warning">Distance unavailable</span>' ?></div></div><div class="score-total"><?= number_format((float)$candidate['total_rating'],2) ?></div></div><ul class="match-explain"><?php foreach($candidate['match_explanation'] as $reason): ?><li><?= clean($reason) ?></li><?php endforeach; ?></ul><details><summary>Score breakdown</summary><p>Education <?= number_format((float)$candidate['education'],2) ?> · Training <?= number_format((float)$candidate['training'],2) ?> · Experience <?= number_format((float)$candidate['experience'],2) ?> · LET/PBET <?= number_format((float)$candidate['let_pbet_rating'],2) ?> · COI <?= number_format((float)$candidate['coi'],2) ?> · NCOI <?= number_format((float)$candidate['ncoi'],2) ?></p></details><?php if(canManageSubstituteAssignments()): ?><form method="POST" action="<?= APP_URL ?>/actions/manage_substitute_assignment.php" style="display:flex;gap:8px;align-items:end;flex-wrap:wrap;margin-top:8px;"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="assign"><input type="hidden" name="request_id" value="<?= $tokenId ?>"><input type="hidden" name="applicant_id" value="<?= (int)$candidate['id'] ?>"><input type="hidden" name="submission_token" value="<?= bin2hex(random_bytes(32)) ?>"><div class="form-group" style="flex:1;min-width:240px"><label class="form-label">Selection remarks <?= $candidate['distance']['distance_km']===null?'(required documented distance override)':'' ?></label><input class="form-input" name="selection_remarks" maxlength="1000" <?= $candidate['distance']['distance_km']===null?'required minlength="10"':'' ?>></div><button class="btn btn-primary">Review & Confirm Assignment</button></form><?php endif; ?></article><?php endforeach; ?><?php if(!$candidates): ?><div class="alert alert-warning">No exact specialization match is currently available, or distances have not yet been calculated. The system will not select an unrelated applicant automatically.</div><?php endif; ?>
<?php if(isAdmin()): ?><?php $over=$db->prepare("SELECT a.id,a.application_code,a.last_name,a.first_name,sp.name specialization_name FROM teacher_applicants a INNER JOIN teacher_specializations sp ON sp.id=a.specialization_id INNER JOIN applicant_application_statuses aps ON aps.id=a.application_status_id AND aps.is_qualified=1 INNER JOIN applicant_availability_statuses av ON av.id=a.availability_status_id WHERE a.is_active=1 AND av.code='available' AND (a.level<>? OR a.specialization_id<>?) ORDER BY a.last_name LIMIT 200");$over->execute([$request['level'],$request['specialization_id']]);$overrideCandidates=$over->fetchAll(PDO::FETCH_ASSOC); ?><details class="privacy-note"><summary>Administrator manual eligibility override</summary><form method="POST" action="<?= APP_URL ?>/actions/manage_substitute_assignment.php" class="applicant-grid" style="margin-top:10px"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="assign"><input type="hidden" name="request_id" value="<?= $tokenId ?>"><input type="hidden" name="manual_override" value="1"><input type="hidden" name="submission_token" value="<?= bin2hex(random_bytes(32)) ?>"><select class="form-select" name="applicant_id" required><option value="">Select non-matching qualified applicant</option><?php foreach($overrideCandidates as $candidate): ?><option value="<?= (int)$candidate['id'] ?>"><?= clean($candidate['application_code'].' · '.$candidate['last_name'].', '.$candidate['first_name'].' · '.$candidate['specialization_name']) ?></option><?php endforeach; ?></select><input class="form-input" name="manual_override_reason" minlength="10" maxlength="1000" required placeholder="Mandatory elevated-permission justification"><input class="form-input" name="selection_remarks" maxlength="1000" required placeholder="Selection/distance remarks"><button class="btn btn-danger">Confirm Manual Override</button></form></details><?php endif; ?>
</section><?php endif; ?>
<?php $as=$db->prepare('SELECT sa.*,a.application_code,a.last_name,a.first_name FROM substitute_assignments sa INNER JOIN teacher_applicants a ON a.id=sa.applicant_id WHERE sa.substitute_request_id=? ORDER BY sa.assigned_at DESC');$as->execute([$tokenId]);$requestAssignments=$as->fetchAll(PDO::FETCH_ASSOC); ?><section class="glass-card applicant-section"><h3>Assignments</h3><div class="table-scroll"><table class="data-table"><thead><tr><th>Applicant</th><th>Status</th><th>Dates</th><th>Distance</th><th>Assigned</th></tr></thead><tbody><?php foreach($requestAssignments as $a): ?><tr><td><?= clean($a['application_code'].' · '.$a['last_name'].', '.$a['first_name']) ?></td><td><?= $badge($a['assignment_status']) ?></td><td><?= clean($a['start_date'].' to '.$a['expected_end_date']) ?></td><td><?= $a['road_distance_km']!==null?number_format((float)$a['road_distance_km'],2).' km':'Unavailable' ?></td><td><?= clean($a['assigned_at']) ?></td></tr><?php endforeach; ?><?php if(!$requestAssignments): ?><tr><td colspan="5" class="text-center text-muted">No confirmed assignments.</td></tr><?php endif; ?></tbody></table></div></section>
<?php endif; ?>

<?php elseif ($view === 'compare'): ?>
<?php
$schoolId=$decodeId(trim((string)($_GET['school']??'')));$st=$db->prepare('SELECT s.*,d.district_name FROM schools s LEFT JOIN districts d ON d.id=s.district_id WHERE s.id=? AND '.activeArchiveExclusion('school','s.id'));$st->execute([$schoolId]);$school=$st->fetch(PDO::FETCH_ASSOC);
if(!$school||($scope!==null&&$scope!==(int)$school['district_id'])): ?><div class="alert alert-error">School not found or outside your district.</div>
<?php else:
$people=[];$q=$db->prepare("SELECT 'applicant' origin_type,a.id,a.last_name,a.first_name,l.barangay,l.municipality,d.district_name FROM teacher_applicants a INNER JOIN teacher_applicant_locations l ON l.applicant_id=a.id INNER JOIN districts d ON d.id=a.district_id INNER JOIN applicant_availability_statuses av ON av.id=a.availability_status_id WHERE a.is_active=1 AND av.code='available'".($scope!==null?' AND a.district_id=?':'').' ORDER BY a.last_name LIMIT 300');$q->execute($scope!==null?[$scope]:[]);$people=array_merge($people,$q->fetchAll(PDO::FETCH_ASSOC));$q=$db->prepare("SELECT 'teacher' origin_type,t.id,t.last_name,t.first_name,t.barangay,t.municipality,d.district_name FROM teachers t LEFT JOIN schools s ON s.id=t.school_id LEFT JOIN districts d ON d.id=s.district_id WHERE ".activeArchiveExclusion('teacher','t.id').($scope!==null?' AND s.district_id=?':'').' ORDER BY t.last_name LIMIT 300');$q->execute($scope!==null?[$scope]:[]);$people=array_merge($people,$q->fetchAll(PDO::FETCH_ASSOC));$saved=$_SESSION['distance_compare'][$schoolId]??[];$savedOrigins=((int)($saved['expires_at']??0)>=time()&&is_array($saved['origins']??null))?$saved['origins']:[];$resultRows=[];foreach($savedOrigins as $origin){foreach($people as $person){if($person['origin_type']===$origin['type']&&(int)$person['id']===(int)$origin['id']){$person['distance']=cachedRouteDistance($db,$origin['type'],(int)$origin['id'],$schoolId)??unavailableDistance('not_calculated');$resultRows[]=$person;break;}}}
?>
<section class="glass-card applicant-section"><h2>Compare Teacher Distance — <?= clean($school['school_name']) ?></h2><p class="privacy-note">Distances are approximate road routes between the selected residence barangay and the school barangay. No latitude, longitude, or residential map marker is used.</p><div class="applicant-grid"><div><strong>School barangay</strong><p><?= clean(($school['barangay'] ?: 'Not set') . ', ' . ($school['municipality'] ?: 'Aurora')) ?></p></div><div><strong>Precision</strong><p>Barangay approximation</p></div></div></section>
<?php if (trim((string)($school['barangay'] ?? '')) === ''): ?><div class="alert alert-warning">This school has no barangay yet. Edit the school address and select its PSGC barangay before calculating approximate routes.</div><?php endif; ?>
<form method="POST" action="<?= APP_URL ?>/actions/applicant_distance.php" class="glass-card applicant-section"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="calculate_compare"><input type="hidden" name="school_id" value="<?= $schoolId ?>"><h3>Select Teachers or Available Applicants</h3><div class="table-scroll" style="max-height:380px"><table class="data-table"><thead><tr><th></th><th>Type</th><th>Name</th><th>Area</th><th>District</th></tr></thead><tbody><?php foreach($people as $person): ?><tr><td><input type="checkbox" name="origins[]" value="<?= clean($person['origin_type'].':'.$person['id']) ?>"></td><td><?= $badge($person['origin_type']) ?></td><td><?= clean($person['last_name'].', '.$person['first_name']) ?></td><td><?= clean(($person['barangay']?:'—').', '.($person['municipality']?:'—')) ?></td><td><?= clean($person['district_name']?:'—') ?></td></tr><?php endforeach; ?></tbody></table></div><div class="modal-actions"><button class="btn btn-primary"><i class="fas fa-route"></i> Calculate Selected Distances</button></div></form>
<?php if($resultRows): ?><section class="glass-card applicant-section"><h3>Comparison Results</h3><div class="table-scroll"><table class="data-table"><thead><tr><th>Name</th><th>Area</th><th>District</th><th>Road Distance</th><th>Travel Time</th><th>Status</th></tr></thead><tbody><?php foreach($resultRows as $person): ?><tr><td><?= clean($person['last_name'].', '.$person['first_name']) ?></td><td><?= clean(($person['barangay']?:'—').', '.($person['municipality']?:'—')) ?></td><td><?= clean($person['district_name']?:'—') ?></td><td><?= $person['distance']['distance_km']!==null?number_format((float)$person['distance']['distance_km'],2).' km':'Distance unavailable' ?></td><td><?= clean(formatTravelTime($person['distance']['travel_time_seconds'])) ?></td><td><?= clean($person['distance']['status']) ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php endif; ?>

<?php else: ?>
<?php if ($tab === 'applicants'):
$q = trim((string)($_GET['q'] ?? ''));
$level = trim((string)($_GET['level'] ?? ''));
$specializationFilter = max(0, (int)($_GET['specialization'] ?? 0));
$districtFilter = max(0, (int)($_GET['district'] ?? 0));
$applicationFilter = max(0, (int)($_GET['application_status'] ?? 0));
$availability = max(0, (int)($_GET['availability'] ?? 0));
$where = ['1=1'];
$params = [];
if ($scope !== null) { $where[] = 'a.district_id=?'; $params[] = $scope; }
if ($q !== '') { $where[] = "(a.application_code LIKE ? OR CONCAT(a.last_name,' ',a.first_name) LIKE ? OR CONCAT(a.first_name,' ',a.last_name) LIKE ?)"; $params[]='%'.$q.'%'; $params[]='%'.$q.'%'; $params[]='%'.$q.'%'; }
if (in_array($level, ['elementary','jhs','shs'], true)) { $where[]='a.level=?'; $params[]=$level; }
if ($specializationFilter > 0) { $where[]='a.specialization_id=?'; $params[]=$specializationFilter; }
if ($districtFilter > 0 && $scope === null) { $where[]='a.district_id=?'; $params[]=$districtFilter; }
if ($applicationFilter > 0) { $where[]='a.application_status_id=?'; $params[]=$applicationFilter; }
if ($availability > 0) { $where[]='a.availability_status_id=?'; $params[]=$availability; }
$count = $db->prepare('SELECT COUNT(*) FROM teacher_applicants a WHERE '.implode(' AND ',$where));
$count->execute($params);
$page = max(1, (int)($_GET['page'] ?? 1));
$pag = paginate((int)$count->fetchColumn(), $page);
$sql = 'SELECT a.*,sp.name specialization_name,d.district_name,aps.label application_status,avs.label availability_status,sc.total_rating
 FROM teacher_applicants a
 INNER JOIN teacher_specializations sp ON sp.id=a.specialization_id
 INNER JOIN districts d ON d.id=a.district_id
 INNER JOIN applicant_application_statuses aps ON aps.id=a.application_status_id
 INNER JOIN applicant_availability_statuses avs ON avs.id=a.availability_status_id
 INNER JOIN teacher_applicant_scores sc ON sc.applicant_id=a.id
 WHERE '.implode(' AND ',$where).' ORDER BY a.last_name,a.first_name LIMIT '.$pag['per_page'].' OFFSET '.$pag['offset'];
$st=$db->prepare($sql); $st->execute($params); $rows=$st->fetchAll(PDO::FETCH_ASSOC);
$filterQuery = ['q'=>$q,'level'=>$level,'specialization'=>$specializationFilter,'district'=>$districtFilter,'application_status'=>$applicationFilter,'availability'=>$availability];
?>
<form class="filter-bar glass-card" method="GET" style="flex-wrap:wrap" data-live-search-form>
    <input class="form-input" name="q" value="<?= clean($q) ?>" placeholder="Search name or application code" data-live-search-input autocomplete="off">
    <select class="form-select" name="level"><option value="">All levels</option><?php foreach($levelLabels as $key=>$label): ?><option value="<?= $key ?>" <?= $level===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select>
    <select class="form-select" name="specialization"><option value="0">All specializations</option><?php foreach($refs['specializations'] as $spec): ?><option value="<?= (int)$spec['id'] ?>" <?= $specializationFilter===(int)$spec['id']?'selected':'' ?>><?= clean($spec['name']) ?></option><?php endforeach; ?></select>
    <?php if($scope===null): ?><select class="form-select" name="district"><option value="0">All districts</option><?php foreach($districts as $district): ?><option value="<?= (int)$district['id'] ?>" <?= $districtFilter===(int)$district['id']?'selected':'' ?>><?= clean($district['district_name']) ?></option><?php endforeach; ?></select><?php endif; ?>
    <select class="form-select" name="application_status"><option value="0">All application statuses</option><?php foreach($refs['application_statuses'] as $status): ?><option value="<?= (int)$status['id'] ?>" <?= $applicationFilter===(int)$status['id']?'selected':'' ?>><?= clean($status['label']) ?></option><?php endforeach; ?></select>
    <select class="form-select" name="availability"><option value="0">All availability</option><?php foreach($refs['availability_statuses'] as $status): ?><option value="<?= (int)$status['id'] ?>" <?= $availability===(int)$status['id']?'selected':'' ?>><?= clean($status['label']) ?></option><?php endforeach; ?></select>
    <button class="btn btn-primary">Filter</button>
</form>
<div data-live-search-results="applicants">
<div class="table-card glass-card"><div class="table-scroll"><table class="data-table">
<thead><tr><th>Application Code</th><th>Applicant</th><th>Level</th><th>Specialization</th><th>District</th><th>Application Status</th><th>Availability</th><th>Total Rating</th><th>Actions</th></tr></thead>
<tbody><?php foreach($rows as $row): ?><tr><td><?= clean($row['application_code']) ?></td><td><?= clean($row['last_name'].', '.$row['first_name'].' '.$row['middle_name']) ?></td><td><?= clean($levelLabels[$row['level']]??$row['level']) ?></td><td><?= clean($row['specialization_name']) ?></td><td><?= clean($row['district_name']) ?></td><td><?= $badge($row['application_status']) ?></td><td><?= $badge($row['availability_status']) ?></td><td><?= number_format((float)$row['total_rating'],2) ?></td><td><a class="btn btn-ghost btn-sm" href="<?= APP_URL ?>/applicants.php?view=applicant&id=<?= urlencode(encryptId((int)$row['id'])) ?>">View</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="9" class="text-center text-muted">No applicants found.</td></tr><?php endif; ?></tbody>
</table></div></div>
<?= paginationLinks($pag, APP_URL.'/applicants.php?'.http_build_query($filterQuery)) ?>
</div>
<?php elseif($tab==='requests'):
$sql='SELECT sr.*,s.school_name,d.district_name,sp.name specialization_name FROM substitute_requests sr INNER JOIN schools s ON s.id=sr.school_id INNER JOIN districts d ON d.id=sr.school_district_id INNER JOIN teacher_specializations sp ON sp.id=sr.specialization_id WHERE 1=1';$params=[];if($scope!==null){$sql.=' AND sr.school_district_id=?';$params[]=$scope;}$sql.=' ORDER BY sr.requested_at DESC LIMIT 250';$st=$db->prepare($sql);$st->execute($params);$rows=$st->fetchAll(PDO::FETCH_ASSOC); ?>
<div class="table-card glass-card"><div class="table-scroll"><table class="data-table"><thead><tr><th>Request</th><th>School</th><th>District</th><th>Level / Specialization</th><th>Leave Period</th><th>Slots</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= clean($row['request_code']) ?></td><td><?= clean($row['school_name']) ?></td><td><?= clean($row['district_name']) ?></td><td><?= clean(($levelLabels[$row['level']]??$row['level']).' · '.$row['specialization_name']) ?></td><td><?= clean($row['leave_start_date'].' to '.$row['expected_end_date']) ?></td><td><?= (int)$row['substitutes_needed'] ?></td><td><?= $badge($row['status']) ?></td><td><a class="btn btn-ghost btn-sm" href="<?= APP_URL ?>/applicants.php?view=request&id=<?= urlencode(encryptId((int)$row['id'])) ?>">Open</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="8" class="text-center text-muted">No substitute requests.</td></tr><?php endif; ?></tbody></table></div></div>
<?php else:
$activeTab=$tab==='active';$statuses=$activeTab?["scheduled","active"]:["completed","cancelled","ended_early"];$placeholders=implode(',',array_fill(0,count($statuses),'?'));$sql="SELECT sa.*,a.application_code,a.last_name,a.first_name,s.school_name,d.district_name,sr.request_code FROM substitute_assignments sa INNER JOIN teacher_applicants a ON a.id=sa.applicant_id INNER JOIN schools s ON s.id=sa.school_id INNER JOIN districts d ON d.id=s.district_id INNER JOIN substitute_requests sr ON sr.id=sa.substitute_request_id WHERE sa.assignment_status IN ($placeholders)";$params=$statuses;if($scope!==null){$sql.=' AND s.district_id=?';$params[]=$scope;}$sql.=' ORDER BY sa.assigned_at DESC LIMIT 250';$st=$db->prepare($sql);$st->execute($params);$rows=$st->fetchAll(PDO::FETCH_ASSOC); ?>
<div class="table-card glass-card"><div class="table-scroll"><table class="data-table"><thead><tr><th>Request</th><th>Applicant</th><th>School</th><th>Period</th><th>Distance Used</th><th>Status</th><?php if($activeTab&&canManageApplicants()): ?><th>Close Assignment</th><?php endif; ?></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= clean($row['request_code']) ?></td><td><?= clean($row['application_code'].' · '.$row['last_name'].', '.$row['first_name']) ?></td><td><?= clean($row['school_name'].' · '.$row['district_name']) ?></td><td><?= clean($row['start_date'].' to '.$row['expected_end_date']) ?></td><td><?= $row['road_distance_km']!==null?number_format((float)$row['road_distance_km'],2).' km':'Unavailable' ?></td><td><?= $badge($row['assignment_status']) ?></td><?php if($activeTab&&canManageApplicants()): ?><td><form method="POST" action="<?= APP_URL ?>/actions/manage_substitute_assignment.php" style="display:flex;gap:5px"><input type="hidden" name="csrf_token" value="<?= csrfToken() ?>"><input type="hidden" name="action" value="close"><input type="hidden" name="assignment_id" value="<?= (int)$row['id'] ?>"><input type="date" class="form-input" name="actual_end_date" value="<?= date('Y-m-d') ?>" required><select class="form-select" name="status"><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="ended_early">Ended Early</option></select><button class="btn btn-primary btn-sm">Save</button></form></td><?php endif; ?></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="7" class="text-center text-muted">No assignments in this tab.</td></tr><?php endif; ?></tbody></table></div></div>
<?php endif; ?>
<?php endif; ?>

<?php require_once dirname(__DIR__, 3) . '/includes/footer.php'; ?>
